### ISSUE TITLE
Can't build on ArchLinux

### ISSUE THREAD

**Issue by Eeems** [TC01/calcpkg#2]
I tried to run setup.py on Archlinux a couple days ago and it was giving me syntax errors. If I switched the python version I was using for it the syntax errors in setup.py went away but there was a ton of errors in the actual build process. I'm not at my computer so I can't give a proper error log until later this week.

**Comment by TC01** [comment]
Posting that error log would be appreciated.

I'll try to take a look at this over the next few days- I have some idea as to what the problem might be but I've yet to attempt to track it down.

I'll also push a commit making both the build script and calcpkg itself be invoked with python2 rather than just python.

**Comment by TC01** [comment]
So, I can't seem to reproduce this in Arch- as long as I run with "python2", setup.py from master works fine, eg:

`$ python2 setup.py build`
`$ sudo python2 setup.py install`

I may still change the `#!/usr/bin/env python` invocation to `#/usr/bin/env python2`, though.

But without any more details, I'm afraid all I can say is that I can't reproduce this error.

**Comment by Eeems** [comment]
I'll have to update my arch partition and try again to see if it still wont build. I might not get that in tonight. It is new years after all.

**Comment by Eeems** [comment]
Seems to be fixed.
