### ISSUE TITLE
No tag

### ISSUE THREAD

**Issue by Eeems** [TC01/calcpkg#3]
I'm working on an [automated build system](https://github.com/Eeems/omni-repo) for my arch repository, and I noticed there isn't even a base level tag so I know what version to make this package automatically when I build it.

**Comment by TC01** [comment]
Sorry about this- the versioning here has become kind of a mess since I moved to github.

I _think_ the first commit matches v1.1, which is what's on ticalc.org, but I'm not positive about this so I just slapped v1.2 on it.

My intention was always to release v2.0 with multi-repo support (for Omnimaga and Cemetech), a saner overall structure, cleaner output, and other general improvements. That's mostly been done over the past... um, two years now, but I still don't have support for either Omnimaga or Cemetech- and thus I've been reluctant to "release" 2.0.

In any case, the current version is now v1.9- this is with most of my improvements and with Kerm's Sandpaper changes (it should be the version that Sandpaper is running, I think). 

I'm not terribly experienced with git tagging, so let me know if you need me to do something else (I just ran "git tag" twice and pushed)- I'll leave this open for now.

**Comment by Eeems** [comment]
FYI: Omnimaga's repo is going to become read only (So a different format) sometime in the near future. I'll try to make an easy API for it so you can retrieve listings etc. After that we are still not sure what is going to happen to it.

Also, the tags are now there, so closing.
